{% set version = "1.3.4" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 4a0f072ae5bdf9270c7450e452f93a6c5c91d888114e8d78868a8f163b0dbb15

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  summary: 'GPX file parser and GPS track manipulation library.'

extra:
  recipe-maintainers:
    - ocefpaf
