{% set version = "1.3.1" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 3e2b9417fdc3d01df7bf93d8eadd7b17ac0f50a6b020b243116a78e7fbf7f78b

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  summary: 'GPX file parser and GPS track manipulation library.'

extra:
  recipe-maintainers:
    - ocefpaf
