{% set version = "1.4.0" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 17a81583babd2d82f92a0141680c2ada774cb92516cc0efe22a246673cc3bbcd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'GPX file parser and GPS track manipulation library'

extra:
  recipe-maintainers:
    - ocefpaf
