{% set version = "1.3.0" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 9673914f164c2a8b066b69a15c7a8e26e0ea5bd6f511e97ec2a6f4f6c8e165a4

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  summary: 'GPX file parser and GPS track manipulation library.'

extra:
  recipe-maintainers:
    - ocefpaf
