{% set version = "1.3.2" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 38f5a194092c5ae9a2c5c60f7cd4b51b76e1f7e2c0990ae4a3495b5c09178e32

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  summary: 'GPX file parser and GPS track manipulation library.'

extra:
  recipe-maintainers:
    - ocefpaf
