{% set version = "1.3.5" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: b09e3212c9af83188d308214428c20c57b4ec1d45c3a3fc40f4b3d49c758aebf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - gpxpy

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'GPX file parser and GPS track manipulation library'

extra:
  recipe-maintainers:
    - ocefpaf
