travis:
  secure:
    BINSTAR_TOKEN: MNAtD2HAaT9Dps8xC7D3nUNIJeJq9mKnVSvX0zBRBkriuu4Bh0qvijXbHwT4pzfaFpRH76Dh0oQzeO4681y7c8VftLl8iV95m0mcqYbjrs5h9Lu1DTlmCU7nwV1Y+9DXWHpCYk+rjuebwJ1md3q5SonZlHQCNQkZzv8kK8rJNhr3t8B3xYqj8Dz+7m+X8PyuuZm1TkxR67OkH4hMVlvm0CL4zJRwrYEB4H5334nrmBYhi8OE1f7iFVQKi1vR3H/JEq38Z22/LTwair5BRGg5Pk20MwjdmCgiq32hiQfhaxoA1+L6xv/hwsZ9bjGyEG41Vo9SSFlJwTmbFJbpNuWHe6KpEV5IyiyF9O6o83RQNSYA97OGLnmorZrCVzLEOpa6ZL9aauD8UZe2cmfeFWSX7prdV2mwfT0izmQE80lq4fqDqtYz+gPWdrsdFxpyOhv4yNasvrzsLby2iUE2o/Jt05pamJvrtKvojGYbZ/muoRVgzU0x7s5G9+gDQwJx60NnkYNU9Ee0GM8DFVnTtIYruI1SPjQZIz5bm/xzDcyzB8oQHbDRgr6vUhyXFX2pCturONME4xWRxKC2mG+CZuhnG+h6hLT7xQyohh+26NfoNJlv5NO5BaghdTQI3OcXPgck0IsdI8mIugkrGeifYFDU21mTaZkSASF9pbFgAZPZZOw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
